# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
workspace 'ios_renderer_opengles2_client'
project 'client.xcodeproj'
def settings
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'iOSObjectiveCFoundation', git: 'https://github.com/ucreates/ios_foundation/', branch: 'master'
  pod 'iOSObjectiveCGLES2Renderer', git: 'https://github.com/ucreates/ios_renderer/', branch: 'master'
end
#target 'iOSObjectiveCTestClinet' do
target 'iOSObjectiveCClinet' do
  settings
end
